version: v1
schema_id: http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2025/01/01/JednostkaMała
unit: PLN
metrics:
  bs_total_assets:
    xpaths:
      - Bilans/Aktywa/SumaAktywow
    transform: first
    sign_rule: none
  bs_fixed_assets:
    xpaths:
      - Bilans/Aktywa/AktywaTrawe/RazemAktywaTrawe
    transform: first
    sign_rule: none
  bs_current_assets:
    xpaths:
      - Bilans/Aktywa/AktywaObrotowe/RazemAktywaObrotowe
    transform: first
    sign_rule: none
  bs_equity_total:
    xpaths:
      - Bilans/Pasywa/KapitalWlasny/RazemKapitalWlasny
    transform: first
    sign_rule: none
  bs_total_liabilities:
    xpaths:
      - Bilans/Pasywa/Zobowiazania/RazemZobowiazania
    transform: first
    sign_rule: none
  bs_short_term_liabilities:
    xpaths:
      - Bilans/Pasywa/Zobowiazania/ZobowiazaniaKrotkoterminowe
    transform: first
    sign_rule: none
  pl_revenue:
    xpaths:
      - RZiS/PrzychodyNetto
    transform: first
    sign_rule: none
  pl_operating_profit:
    xpaths:
      - RZiS/ZyskStrataNaDzialalnosci
    transform: first
    sign_rule: none
  pl_net_income:
    xpaths:
      - RZiS/WynikFinansowyNetto
    transform: first
    sign_rule: none
